/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Cocina;
import Salon.Pedido;
import Salon.Hamburguesa;

/**
 *
 * @author dario
 */
public class PedidoCocina extends javax.swing.JPanel {
    CocinaClassInterfaz cocina;
    Pedido pedido;

    /**
     * Creates new form PedidoCocina
     */
    public PedidoCocina(Pedido _pedido, CocinaClassInterfaz _cocina) {
        cocina = _cocina;
        pedido = _pedido;
        initComponents();
        LabelNumMesa.setText("Mesa: " + pedido.getIdMesa());
        LabelNumPedido.setText("Pedido: " + pedido.getID());
        String stringTypeBurgers = "";
        for (Hamburguesa burger : _pedido.getArrayHamburguesas()){
            stringTypeBurgers += burger.getType() + "\n";
        }
        LabelTypeBurger.setText(stringTypeBurgers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IamgenPedido = new javax.swing.JLabel();
        LabelNumPedido = new javax.swing.JLabel();
        LabelNumMesa = new javax.swing.JLabel();
        LabelTypeBurger = new javax.swing.JLabel();
        BotonListo = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(135, 130));
        setPreferredSize(new java.awt.Dimension(135, 130));
        setRequestFocusEnabled(false);

        IamgenPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pedido.png"))); // NOI18N
        IamgenPedido.setDoubleBuffered(true);

        LabelNumPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNumPedido.setText("Pedido: #");

        LabelNumMesa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelNumMesa.setText("Mesa: #");

        LabelTypeBurger.setText("TipoBurguer");

        BotonListo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BotonListo.setText("Listo");
        BotonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IamgenPedido)
                    .addComponent(LabelNumMesa)
                    .addComponent(LabelNumPedido)
                    .addComponent(BotonListo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTypeBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IamgenPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(LabelNumPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelNumMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonListo))
            .addComponent(LabelTypeBurger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void BotonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListoActionPerformed
        // TODO add your handling code here:
        this.cocina.devolverPedido(pedido);
    }//GEN-LAST:event_BotonListoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonListo;
    private javax.swing.JLabel IamgenPedido;
    private javax.swing.JLabel LabelNumMesa;
    private javax.swing.JLabel LabelNumPedido;
    private javax.swing.JLabel LabelTypeBurger;
    // End of variables declaration//GEN-END:variables
}
